enyo.depends(
  "$lib/jquery",
  "../../client/lib/underscore/underscore-min.js",
  "../../client/lib/backbone/backbone-min.js",
  "../../client/source/core.js",
	"../../client/source/xt",
  "stylesheets/screen.css",
  "$lib/layout",
  "App.js",
  "Core.js",
  "views"
);